print("       |       |      ")
print("   O   |   X   |   X  ")
print("       |       |      ")
print("-------+-------+-------")
print("       |       |      ")
print("   X   |   O   |   X  ")
print("       |       |      ")
print("-------+-------+-------")
print("       |       |      ")
print("   X   |   O   |   O  ")
print("       |       |      ")
